# Tratamento e Padronização dos Dados(Use os dados da pasta dada/unfiltered)

In [92]:
import pandas as pd

# caminho do arquivo
caminho_csv_1 = "/home/gabrielr1b/Faculdade/ICD/Trabalho/Gabriel 04-04-2026/Openess to Travel and Tourism/Openess_to_travel_and_tourism_data.csv"

# carregar como DataFrame
df = pd.read_csv(caminho_csv_1, low_memory=False)
caminho_csv_2 = "/home/gabrielr1b/Faculdade/ICD/Trabalho/Gabriel 04-04-2026/data_filtered/continentes.csv"
df_cont = pd.read_csv(caminho_csv_2, low_memory=False)


# visualizar
df.head()

,FREQ,FREQ_LABEL,REF_AREA,REF_AREA_LABEL,INDICATOR,INDICATOR_LABEL,UNIT_MEASURE,UNIT_MEASURE_LABEL,TYPE,TYPE_LABEL,...,DATABASE_ID_LABEL,UNIT_MULT,UNIT_MULT_LABEL,OBS_STATUS,OBS_STATUS_LABEL,OBS_CONF,OBS_CONF_LABEL,2019,2021,2024
0,A,Annual,AGO,Angola,WEF_TTDI_TTDI_B_07,"Openness to Travel and Tourism, 1-7 (best)",IX_1T7,Score 1-7,WEF_TTDI_RNK,Type: Rank,...,Travel & Tourism Development Index (TTDI),0,Units,A,Normal value,PU,Public,116.000000,116.000000,112.000000
1,A,Annual,AGO,Angola,WEF_TTDI_TTDI_B_07,"Openness to Travel and Tourism, 1-7 (best)",IX_1T7,Score 1-7,WEF_TTDI_SCR,Type: Score,...,Travel & Tourism Development Index (TTDI),0,Units,A,Normal value,PU,Public,2.199659,2.208469,2.584328
2,A,Annual,AGO,Angola,WEF_TTDI_TTDI_B_07,"Openness to Travel and Tourism, 1-7 (best)",IX_1T7,Score 1-7,WEF_TTDI_VAL,Type: Value,...,Travel & Tourism Development Index (TTDI),0,Units,A,Normal value,PU,Public,2.199659,2.208469,2.584328
3,A,Annual,ALB,Albania,WEF_TTDI_TTDI_B_07,"Openness to Travel and Tourism, 1-7 (best)",IX_1T7,Score 1-7,WEF_TTDI_RNK,Type: Rank,...,Travel & Tourism Development Index (TTDI),0,Units,A,Normal value,PU,Public,80.000000,78.000000,39.000000
4,A,Annual,ALB,Albania,WEF_TTDI_TTDI_B_07,"Openness to Travel and Tourism, 1-7 (best)",IX_1T7,Score 1-7,WEF_TTDI_SCR,Type: Score,...,Travel & Tourism Development Index (TTDI),0,Units,A,Normal value,PU,Public,3.559038,3.609038,4.557484

In [93]:
df.columns

Index(['FREQ', 'FREQ_LABEL', 'REF_AREA', 'REF_AREA_LABEL', 'INDICATOR',
       'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'TYPE',
       'TYPE_LABEL', 'DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT',
       'UNIT_MULT_LABEL', 'OBS_STATUS', 'OBS_STATUS_LABEL', 'OBS_CONF',
       'OBS_CONF_LABEL', '2019', '2021', '2024'],
      dtype='object')

In [94]:
#Padronização dos dados- Remoção de Colunas Irrelevantes
df = df.drop(['FREQ','FREQ_LABEL','INDICATOR',
       'INDICATOR_LABEL', 'UNIT_MEASURE', 'UNIT_MEASURE_LABEL', 'TYPE','DATABASE_ID', 'DATABASE_ID_LABEL', 'UNIT_MULT',
       'UNIT_MULT_LABEL', 'OBS_STATUS', 'OBS_STATUS_LABEL','OBS_CONF',
       'OBS_CONF_LABEL'], axis = 1 )

In [95]:
df = df.melt(
    id_vars=["REF_AREA", "REF_AREA_LABEL", "TYPE_LABEL"],
    var_name="YEAR",
    value_name="VALUE"
)

In [96]:
df = df.pivot_table(
    index=["REF_AREA", "REF_AREA_LABEL", "YEAR"],
    columns="TYPE_LABEL",
    values="VALUE"
).reset_index()

In [97]:
df.rename(columns={
    "REF_AREA": "Sigla",
    "REF_AREA_LABEL": "País",
    "Type: Rank" : "Rank",
    "Type: Value" : "Valor Bruto",
    "Type: Score" : "Pontuação Final",
    "YEAR" : "Ano"
}, inplace=True)

In [98]:
df = df[['Sigla',"País",'Ano','Valor Bruto','Pontuação Final','Rank']]

In [99]:
df.head()

TYPE_LABEL Sigla     País   Ano  Valor Bruto  Pontuação Final   Rank
0            AGO   Angola  2019     2.199659         2.199659  116.0
1            AGO   Angola  2021     2.208469         2.208469  116.0
2            AGO   Angola  2024     2.584328         2.584328  112.0
3            ALB  Albania  2019     3.559038         3.559038   80.0
4            ALB  Albania  2021     3.609038         3.609038   78.0

In [100]:
df_cont.head()

  Sigla Continente
0   AFG         AS
1   ALB         EU
2   DZA         AF
3   ASM         OC
4   AND         EU

In [101]:
# remover linhas sem código
df_cont = df_cont[df_cont["Sigla"].notna()]
df_cont = df_cont[df_cont["Sigla"].str.strip() != ""]

# remover espaços
df_cont["Sigla"] = df_cont["Sigla"].str.strip()
df_cont["Continente"] = df_cont["Continente"].str.strip()

In [102]:
df_cont.head()

  Sigla Continente
0   AFG         AS
1   ALB         EU
2   DZA         AF
3   ASM         OC
4   AND         EU

In [103]:
df_merged = df.merge(df_cont, on="Sigla", how="left")

In [104]:
df_merged.head()

  Sigla     País   Ano  Valor Bruto  Pontuação Final   Rank Continente
0   AGO   Angola  2019     2.199659         2.199659  116.0         AF
1   AGO   Angola  2021     2.208469         2.208469  116.0         AF
2   AGO   Angola  2024     2.584328         2.584328  112.0         AF
3   ALB  Albania  2019     3.559038         3.559038   80.0         EU
4   ALB  Albania  2021     3.609038         3.609038   78.0         EU

In [105]:
#Exportação dos dados filtrados
import os

# nome do arquivo
caminho_saida = "/home/gabrielr1b/Faculdade/ICD/Trabalho/Gabriel 04-04-2026/Openess to Travel and Tourism/Openness_to_travel_and_tourism_Data.csv"

# salvar
df_merged.to_csv(caminho_saida, index=False)